name: ci

on:
  push:
    tags:
      - "*"
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: macos-latest
            TARGET: x86_64-apple-darwin

          - os: ubuntu-latest
            TARGET: x86_64-unknown-linux-musl

          - os: windows-latest
            TARGET: x86_64-windows

    name: Build
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Get dependencies
        run: pip3 install requests pyinstaller

      - name: Generate binary
        run: pyinstaller --onefile easydns-restapi-cli -n easydnscli-${{matrix.TARGET}}

      - name: Add binaries to release artifacts
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./dist/easydnscli-${{matrix.TARGET}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
